Tuning up dev scripts
  - `dev/up` is shorter / nicer to type (than `script/start` imo)
  - shore up the _bash_ fodder

diff --git a/dev/init_laravel b/dev/init_laravel
--- a/dev/init_laravel
+++ b/dev/init_laravel
@@ -1,10 +1,14 @@
 #!/usr/bin/env bash
-
-set -x
+#
+# Safe bash settings
+# -e            Exit on command fail
+# -u            Treat unset variables as error
+# -x            Print command before executing
+# -o pipefail   Set error if piped command has error code
+set -e -o pipefail
 
 SCRIPT_DIR=$(dirname "$0")
-
-cd "${SCRIPT_DIR}/.."
+cd "$SCRIPT_DIR/.."
 
 echo "This is very destructive, executes 'rm -rf' on things like: .git, public"
 echo "make sure you have looked over this script and are ok with what it will do"
@@ -43,6 +47,6 @@ git commit -m 'initial laravel commit'
 
 echo
 echo "Review .env file, then:"
-echo " script/start"
-echo " script/artisan make:auth"
-echo " script/artisan migrate"
+echo " dev/up"
+echo " dev/artisan make:auth"
+echo " dev/artisan migrate"
